spring:
  application:
    name: stellflux-jedis-examples

server:
  port: 18084

example:
  jedis:
    host: 127.0.0.1
    port: 6379
    invoke-on-startup: false

stellflux:
  lock:
    jedis:
      host: 127.0.0.1
      port: 6379
      key-prefix: "stellflux:lock:example:"
      default-ttl: 30s
  opentelemetry:
    logs-output: console
    logs-format: json
    metric-export-interval: 10s
    resource:
      service-name: stellflux-jedis-examples
    logs:
      enabled: true
    metrics:
      enabled: true
    traces:
      enabled: true
