spring:
  application:
    name: stellflux-http-server-example

server:
  port: 18080

stellflux:
  opentelemetry:
    resource:
      service-name: stellflux-http-server-example
    logs:
      enabled: false
    metrics:
      enabled: false
    traces:
      enabled: false
