spring:
  application:
    name: http-example

server:
  port: 18081

stellflux:
  stellmap:
    base-url: http://192.168.1.14:8080
  opentelemetry:
    resource:
      service-name: stellhub.examples.http
    logs:
      enabled: false
    metrics:
      enabled: false
    traces:
      enabled: false
