spring:
  application:
    name: stellhub.core.middleware.stellcloud.admin

server:
  port: 18090

stellflux:
  stellnula:
    endpoint: ${STELLNULA_ENDPOINT:http://127.0.0.1:8060}
    namespace: ${STELLNULA_NAMESPACE:app-config}
  opentelemetry:
    resource:
      service-name: ${spring.application.name}
      service-namespace: stellflux-examples
    logs:
      enabled: false
    metrics:
      enabled: false
    traces:
      enabled: false
