spring:
  application:
    name: stellflux-opentelemetry-example

server:
  port: 18083

stellflux:
  opentelemetry:
    logs-output: console
    logs-format: json
    metric-export-interval: 10s
    resource:
      service-name: stellflux-opentelemetry-example
    logs:
      enabled: true
    metrics:
      enabled: true
    traces:
      enabled: true
